### ISSUE TITLE
Make this website Mobile Responsive

### ISSUE THREAD

**Issue by g33kyshivam** [Moz-NIEC/Hacktoberfest#10]
Almost all the content is mobile responsive, used Flexbox.  

Web-view is Fine 
![image](https://user-images.githubusercontent.com/24518185/32088128-abdc7ac8-bafe-11e7-925a-96d4374ffefc.png)

But in small screen size
![image](https://user-images.githubusercontent.com/24518185/32088158-ed7615a2-bafe-11e7-81a5-a8967ef9edb9.png)

Ideally here the the venue and time should stack over (wrap).

**Comment by AntonyFenton** [comment]
I can take this off your hands

**Comment by inyee786** [comment]
hey i want to know whether this is open issue or it is closed?
