### ISSUE TITLE
Make Mobile Responsive

### ISSUE THREAD

**Issue by g33kyshivam** [Moz-NIEC/Hacktoberfest#37]
Web view is fine , but it is breaking in mobile screen size. Make mobile friendly :D

![image](https://user-images.githubusercontent.com/24518185/32115270-c675b394-bb63-11e7-846e-3ab8acea1bf0.png)
![image](https://user-images.githubusercontent.com/24518185/32115283-d4b56e5e-bb63-11e7-8670-08359f2100c7.png)

**Comment by vinodselvin** [comment]
I am taking this issue.

**Comment by championshuttler** [comment]
@vinodselvin sure :) Go ahead

**Comment by vinodselvin** [comment]
#37 Made Mobile Responsive

**Comment by vinodselvin** [comment]
I think we can close this issue now.
